### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Qiu105** [shashadehuajiang/trace_classifier#1]
Hello author, I would like to ask how to use public datasets such as UAV, SWF, KWS with this framework mentioned in the article. Thank you for your reply.

**Comment by shashadehuajiang** [comment]
Hi there! The datasets are not ready for publication yet due to privacy concerns. After obfuscating some fields such as IP addresses, the dataset links will be added to the dataset README file. (According to the schedule, the datasets will be available in about 2 weeks.)

**Comment by Qiu105** [comment]
Thank you very much. Can I use other public datasets to test it, or are there any available public datasets for testing? Looking forward to your reply.


> Hi there! The datasets are not ready for publication yet due to privacy concerns. After obfuscating some fields such as IP addresses, the dataset links will be added to the dataset README file. (According to the schedule, the datasets will be available in about 2 weeks.)

Thank you very much. Can I use other public datasets to test it, or are there any available public datasets for testing? For example, the ISCX-VPN, USTC-TFC, ISCX-Tor datasets, if I want to use these datasets, what format should the data be processed into before inputting?Looking forward to your reply.

**Comment by shashadehuajiang** [comment]
Sure. https://github.com/shashadehuajiang/trace_classifier/blob/main/dataset/generate_a_dataset(sample).py    This file shows an example of how to generate a dataset JSON file.

**Comment by Qiu105** [comment]
> Sure. https://github.com/shashadehuajiang/trace_classifier/blob/main/dataset/generate_a_dataset(sample).py This file shows an example of how to generate a dataset JSON file.
Can I directly use the raw data in pcap format for input?

**Comment by Qiu105** [comment]
> Sure. https://github.com/shashadehuajiang/trace_classifier/blob/main/dataset/generate_a_dataset(sample).py This file shows an example of how to generate a dataset JSON file.

Can I directly use the raw data in pcap format for input?

**Comment by shashadehuajiang** [comment]
Yes, and you need to transfer the raw data of each packet into a packet vector. For example, byte to int (0-256). Note that the first component of a packet vector must be the timestamp.  (One vector v = [timestamp, raw data, raw data, ..., raw data])

**Comment by Qiu105** [comment]
> Yes, and you need to transfer the raw data of each packet into a packet vector. For example, byte to int (0-256). Note that the first component of a packet vector must be the timestamp. (One vector v = [timestamp, raw data, raw data, ..., raw data])

Thank you for your reply.
