### ISSUE TITLE
Processing dataset

### ISSUE THREAD

**Issue by WBSLZF** [shashadehuajiang/trace_classifier#2]
您好作者，请问您是用什么工具切分多流的呢

**Comment by shashadehuajiang** [comment]
我把工具上传了。[dataset_maker](https://github.com/shashadehuajiang/trace_classifier/tree/main/dataset_maker)

**Comment by WBSLZF** [comment]
好的，谢谢巨佬了Orz

**Comment by WBSLZF** [comment]
请问下对于trace的定义，是指某一段时间内的pcap的中按照五元组切分成单流的集合嘛（在切分工具上看大致是这样的），那么有一个问题，在现网中某一段时间中pcap内的flow，不一定是相关的（就是可能是多个应用的流量），这个问题咋解决呢

**Comment by shashadehuajiang** [comment]
可以先使用ip地址、端口一些信息初步过滤。对于没有办法过滤的流量，可以直接保留所有流量（包括不相干的flow），让模型自己学。
