### ISSUE TITLE
Processing dataset

### ISSUE THREAD

**Issue by GAINIBYM** [shashadehuajiang/trace_classifier#4]
您好，我最近才开始学习深度学习，看到了您的文章，我下载了ISD的原来的数据集，我将两种分类的pcap使用dataset_maker的时候最后得到的json文件里面的数据的长度仅为本来pcap文件的个数，而不是文章的4402，请问一下是怎么切分的呢？我需要修改什么才能得到4402个长度的数据吗，期待您的答复解决一下现阶段的问题。

**Comment by GAINIBYM** [comment]
我是修改时间窗口为其他的值就可以么

**Comment by shashadehuajiang** [comment]
我没记错的话是的，可以将时间窗口修改为60s看下对不对

**Comment by GAINIBYM** [comment]
我修改了50在您回复之前，大致是的，我要是使用别的数据集的话是不是设置为多少自己定就可以

**Comment by shashadehuajiang** [comment]
对

**Comment by GAINIBYM** [comment]
好的，谢谢您答复，生活愉快！

**Comment by GAINIBYM** [comment]
为什么我在3060ti上的运行速度会快于于在a800上的速度，这个问题的可能原因是什么？
